SELECT
  DISTINCT
   ATENDIME.CD_ATENDIMENTO,
   ATENDIME.CD_LEITO,
   ATENDIME.CD_PACIENTE,
   ATENDIME.CD_CONVENIO,
   ATENDIME.CD_CID,
   ATENDIME.HR_ATENDIMENTO,
      LEITO.CD_UNID_INT,
   LEITO.DS_LEITO,
   LEITO.DS_RESUMO,
   PACIENTE.NM_PACIENTE,
   PACIENTE.DT_NASCIMENTO,
   UNID_INT.DS_UNID_INT,
   CONVENIO.NM_CONVENIO,
   ATENDIME.CD_ORI_ATE,
   ATENDIME.TP_ATENDIMENTO, 
   CID.DS_CID
   ,( SELECT MOV_CARDAPIO.OBS_NUTRICAO FROM MOV_CARDAPIO
      WHERE MOV_CARDAPIO.CD_MOV_CARDAPIO =
      ( SELECT Max( MOV_CARDAPIO.CD_MOV_CARDAPIO ) FROM MOV_CARDAPIO
        WHERE
          MOV_CARDAPIO.CD_TIPO_REFEICAO = 'ALMO'
          AND MOV_CARDAPIO.CD_ATENDIMENTO = ATENDIME.CD_ATENDIMENTO ) ) OBS_NUTRICAO_ALMO
   ,( SELECT MOV_CARDAPIO.OBS_NUTRICAO FROM MOV_CARDAPIO
      WHERE MOV_CARDAPIO.CD_MOV_CARDAPIO =
      ( SELECT Max( MOV_CARDAPIO.CD_MOV_CARDAPIO ) FROM MOV_CARDAPIO
        WHERE
          MOV_CARDAPIO.CD_TIPO_REFEICAO = 'DESJ'
          AND MOV_CARDAPIO.CD_ATENDIMENTO = ATENDIME.CD_ATENDIMENTO ) ) OBS_NUTRICAO_DESJ
   ,( SELECT MOV_CARDAPIO.OBS_NUTRICAO FROM MOV_CARDAPIO
      WHERE MOV_CARDAPIO.CD_MOV_CARDAPIO =
      ( SELECT Max( MOV_CARDAPIO.CD_MOV_CARDAPIO ) FROM MOV_CARDAPIO
        WHERE
          MOV_CARDAPIO.CD_TIPO_REFEICAO = 'JANTA'
          AND MOV_CARDAPIO.CD_ATENDIMENTO = ATENDIME.CD_ATENDIMENTO ) ) OBS_NUTRICAO_JANT
   ,( SELECT MOV_CARDAPIO.OBS_NUTRICAO FROM MOV_CARDAPIO
      WHERE MOV_CARDAPIO.CD_MOV_CARDAPIO =
      ( SELECT Max( MOV_CARDAPIO.CD_MOV_CARDAPIO ) FROM MOV_CARDAPIO
        WHERE
          MOV_CARDAPIO.CD_TIPO_REFEICAO = 'LANC'
          AND MOV_CARDAPIO.CD_ATENDIMENTO = ATENDIME.CD_ATENDIMENTO ) ) OBS_NUTRICAO_LANC
   ,( SELECT MOV_CARDAPIO.OBS_NUTRICAO FROM MOV_CARDAPIO
      WHERE MOV_CARDAPIO.CD_MOV_CARDAPIO =
      ( SELECT Max( MOV_CARDAPIO.CD_MOV_CARDAPIO ) FROM MOV_CARDAPIO
        WHERE
          MOV_CARDAPIO.CD_TIPO_REFEICAO = 'COLA'
          AND MOV_CARDAPIO.CD_ATENDIMENTO = ATENDIME.CD_ATENDIMENTO ) ) OBS_NUTRICAO_COLA
   ,( SELECT MOV_CARDAPIO.OBS_NUTRICAO FROM MOV_CARDAPIO
      WHERE MOV_CARDAPIO.CD_MOV_CARDAPIO =
      ( SELECT Max( MOV_CARDAPIO.CD_MOV_CARDAPIO ) FROM MOV_CARDAPIO
        WHERE
          MOV_CARDAPIO.CD_TIPO_REFEICAO = 'CEIA'
          AND MOV_CARDAPIO.CD_ATENDIMENTO = ATENDIME.CD_ATENDIMENTO ) ) OBS_NUTRICAO_CEIA
  ,(  
    
    SELECT DS_TIP_PRESC 
      FROM TIP_PRESC 
      WHERE TIP_PRESC.CD_TIP_PRESC = 
    
    ( SELECT MOV_CARDAPIO.CD_TIPO_DIETA FROM MOV_CARDAPIO
      WHERE MOV_CARDAPIO.CD_MOV_CARDAPIO =
      ( SELECT Max( MOV_CARDAPIO.CD_MOV_CARDAPIO ) FROM MOV_CARDAPIO
        WHERE
          MOV_CARDAPIO.CD_TIPO_REFEICAO IN ( 'ALMO', 'DESJ', 'COLA', 'CEIA', 'LANC', 'JANTA' )
          AND MOV_CARDAPIO.CD_ATENDIMENTO = ATENDIME.CD_ATENDIMENTO 
           ) 
        ) 
          ) DS_TIP_PRESC


   

FROM ATENDIME

LEFT OUTER JOIN PACIENTE ON PACIENTE.CD_PACIENTE = ATENDIME.CD_PACIENTE
LEFT OUTER JOIN LEITO ON LEITO.CD_LEITO = ATENDIME.CD_LEITO
LEFT OUTER JOIN CONVENIO ON CONVENIO.CD_CONVENIO = ATENDIME.CD_CONVENIO
LEFT OUTER JOIN UNID_INT ON UNID_INT.CD_UNID_INT = LEITO.CD_UNID_INT
LEFT OUTER JOIN CID ON CID.CD_CID = ATENDIME.CD_CID

WHERE  ATENDIME.TP_ATENDIMENTO IN ( 'I', 'U' )
   AND ( ATENDIME.DT_ALTA IS NULL ) 
   AND ( ATENDIME.CD_LEITO IS NULL AND ( Trunc ( (  SYSDATE - ATENDIME.dt_atendimento )  * 24  , 2) BETWEEN 0 AND 48 ) )

ORDER BY UNID_INT.DS_UNID_INT, LEITO.DS_RESUMO   

-- 4749552
-- 4786358
-- 4762905



