SELECT
   ATENDIME.CD_ATENDIMENTO,
   ATENDIME.CD_LEITO,
   ATENDIME.CD_PACIENTE,
   ATENDIME.CD_CONVENIO,
   ATENDIME.CD_CID,
   LEITO.CD_UNID_INT,
   UNID_INT.DS_UNID_INT,
   CONVENIO.NM_CONVENIO,
   PACIENTE.NM_PACIENTE,
   PACIENTE.DT_NASCIMENTO,
   LEITO.DS_LEITO,
   PACIENTE.NM_PACIENTE,
   ( SELECT MOV_CARDAPIO.OBS_NUTRICAO FROM MOV_CARDAPIO
      WHERE MOV_CARDAPIO.CD_MOV_CARDAPIO =
      ( SELECT Max( MOV_CARDAPIO.CD_MOV_CARDAPIO ) FROM MOV_CARDAPIO
        WHERE
          MOV_CARDAPIO.CD_TIPO_REFEICAO = 'ALMO'
          AND MOV_CARDAPIO.CD_ATENDIMENTO = ATENDIME.CD_ATENDIMENTO ) ) OBS_NUTRICAO_ALMO
   ,( SELECT MOV_CARDAPIO.OBS_NUTRICAO FROM MOV_CARDAPIO
      WHERE MOV_CARDAPIO.CD_MOV_CARDAPIO =
      ( SELECT Max( MOV_CARDAPIO.CD_MOV_CARDAPIO ) FROM MOV_CARDAPIO
        WHERE
          MOV_CARDAPIO.CD_TIPO_REFEICAO = 'DESJ'
          AND MOV_CARDAPIO.CD_ATENDIMENTO = ATENDIME.CD_ATENDIMENTO ) ) OBS_NUTRICAO_DESJ
   ,( SELECT MOV_CARDAPIO.OBS_NUTRICAO FROM MOV_CARDAPIO
      WHERE MOV_CARDAPIO.CD_MOV_CARDAPIO =
      ( SELECT Max( MOV_CARDAPIO.CD_MOV_CARDAPIO ) FROM MOV_CARDAPIO
        WHERE
          MOV_CARDAPIO.CD_TIPO_REFEICAO = 'JANTA'
          AND MOV_CARDAPIO.CD_ATENDIMENTO = ATENDIME.CD_ATENDIMENTO ) ) OBS_NUTRICAO_JANT
   ,( SELECT MOV_CARDAPIO.OBS_NUTRICAO FROM MOV_CARDAPIO
      WHERE MOV_CARDAPIO.CD_MOV_CARDAPIO =
      ( SELECT Max( MOV_CARDAPIO.CD_MOV_CARDAPIO ) FROM MOV_CARDAPIO
        WHERE
          MOV_CARDAPIO.CD_TIPO_REFEICAO = 'LANC'
          AND MOV_CARDAPIO.CD_ATENDIMENTO = ATENDIME.CD_ATENDIMENTO ) ) OBS_NUTRICAO_LANC
   ,( SELECT MOV_CARDAPIO.OBS_NUTRICAO FROM MOV_CARDAPIO
      WHERE MOV_CARDAPIO.CD_MOV_CARDAPIO =
      ( SELECT Max( MOV_CARDAPIO.CD_MOV_CARDAPIO ) FROM MOV_CARDAPIO
        WHERE
          MOV_CARDAPIO.CD_TIPO_REFEICAO = 'COLA'
          AND MOV_CARDAPIO.CD_ATENDIMENTO = ATENDIME.CD_ATENDIMENTO ) ) OBS_NUTRICAO_COLA


FROM ATENDIME

LEFT OUTER JOIN PACIENTE ON PACIENTE.CD_PACIENTE = ATENDIME.CD_PACIENTE
LEFT OUTER JOIN LEITO ON LEITO.CD_LEITO = ATENDIME.CD_LEITO
LEFT OUTER JOIN CONVENIO ON CONVENIO.CD_CONVENIO = ATENDIME.CD_CONVENIO
LEFT OUTER JOIN UNID_INT ON UNID_INT.CD_UNID_INT = LEITO.CD_UNID_INT

WHERE ATENDIME.CD_ATENDIMENTO = 4749552

-- 4749552
-- 4786358
-- 4762905



