SELECT
  ATENDIME.CD_ATENDIMENTO,
   ATENDIME.CD_LEITO,
   ATENDIME.CD_PACIENTE,
   PACIENTE.NM_PACIENTE,
   ( SELECT MOV_CARDAPIO.OBS_NUTRICAO FROM MOV_CARDAPIO
      WHERE MOV_CARDAPIO.CD_MOV_CARDAPIO =
      ( SELECT Max( MOV_CARDAPIO.CD_MOV_CARDAPIO ) FROM MOV_CARDAPIO
        WHERE
          MOV_CARDAPIO.CD_TIPO_REFEICAO = 'ALMO'
          AND MOV_CARDAPIO.CD_ATENDIMENTO = ATENDIME.CD_ATENDIMENTO ) ) OBS_NUTRICAO_ALMO
   ,( SELECT MOV_CARDAPIO.OBS_NUTRICAO FROM MOV_CARDAPIO
      WHERE MOV_CARDAPIO.CD_MOV_CARDAPIO =
      ( SELECT Max( MOV_CARDAPIO.CD_MOV_CARDAPIO ) FROM MOV_CARDAPIO
        WHERE
          MOV_CARDAPIO.CD_TIPO_REFEICAO = 'DESJ'
          AND MOV_CARDAPIO.CD_ATENDIMENTO = ATENDIME.CD_ATENDIMENTO ) ) OBS_NUTRICAO_DESJ
   ,( SELECT MOV_CARDAPIO.OBS_NUTRICAO FROM MOV_CARDAPIO
      WHERE MOV_CARDAPIO.CD_MOV_CARDAPIO =
      ( SELECT Max( MOV_CARDAPIO.CD_MOV_CARDAPIO ) FROM MOV_CARDAPIO
        WHERE
          MOV_CARDAPIO.CD_TIPO_REFEICAO = 'JANT'
          AND MOV_CARDAPIO.CD_ATENDIMENTO = ATENDIME.CD_ATENDIMENTO ) ) OBS_NUTRICAO_JANT
   ,( SELECT MOV_CARDAPIO.OBS_NUTRICAO FROM MOV_CARDAPIO
      WHERE MOV_CARDAPIO.CD_MOV_CARDAPIO =
      ( SELECT Max( MOV_CARDAPIO.CD_MOV_CARDAPIO ) FROM MOV_CARDAPIO
        WHERE
          MOV_CARDAPIO.CD_TIPO_REFEICAO = 'LANC'
          AND MOV_CARDAPIO.CD_ATENDIMENTO = ATENDIME.CD_ATENDIMENTO ) ) OBS_NUTRICAO_LANC
   ,( SELECT MOV_CARDAPIO.OBS_NUTRICAO FROM MOV_CARDAPIO
      WHERE MOV_CARDAPIO.CD_MOV_CARDAPIO =
      ( SELECT Max( MOV_CARDAPIO.CD_MOV_CARDAPIO ) FROM MOV_CARDAPIO
        WHERE
          MOV_CARDAPIO.CD_TIPO_REFEICAO = 'COLA'
          AND MOV_CARDAPIO.CD_ATENDIMENTO = ATENDIME.CD_ATENDIMENTO ) ) OBS_NUTRICAO_COLA


FROM ATENDIME

LEFT OUTER JOIN PACIENTE ON PACIENTE.CD_PACIENTE = ATENDIME.CD_PACIENTE

WHERE ATENDIME.CD_ATENDIMENTO = 4786358

-- 4786358
-- 4762905












